# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '68893fa5-0834-499f-95f9-b4c7933a5c57'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'LogicAppsVnet'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'LAv2-vNet/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'